Starting Container

[2025-07-31 10:10:27 +0000] [1] [INFO] Starting gunicorn 23.0.0

[2025-07-31 10:10:27 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)

[2025-07-31 10:10:27 +0000] [1] [INFO] Using worker: sync

[2025-07-31 10:10:27 +0000] [2] [INFO] Booting worker with pid: 2

[2025-07-31 10:10:27 +0000] [3] [INFO] Booting worker with pid: 3

[2025-07-31 10:10:28 +0000] [2] [ERROR] Exception in worker process

Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/insightface/__init__.py", line 8, in <module>

    import onnxruntime

ModuleNotFoundError: No module named 'onnxruntime'

 

During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker

    worker.init_process()

  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 135, in init_process

    self.load_wsgi()

  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi

    self.wsgi = self.app.wsgi()

  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 66, in wsgi

    self.callable = self.load()

  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 57, in load

    return self.load_wsgiapp()

  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp

    return util.import_app(self.app_uri)

  File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 370, in import_app

    mod = importlib.import_module(module)

  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import

  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load

  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 850, in exec_module

  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

  File "/app/app.py", line 8, in <module>

    import insightface

  File "/usr/local/lib/python3.9/site-packages/insightface/__init__.py", line 10, in <module>

    raise ImportError(

ImportError: Unable to import dependency onnxruntime. 

[2025-07-31 10:10:28 +0000] [3] [ERROR] Exception in worker process

Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/insightface/__init__.py", line 8, in <module>

    import onnxruntime

ModuleNotFoundError: No module named 'onnxruntime'

 

During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker

    worker.init_process()

  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 135, in init_process

    self.load_wsgi()

  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi

    self.wsgi = self.app.wsgi()

  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 66, in wsgi

    self.callable = self.load()

  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 57, in load

    return self.load_wsgiapp()

  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp

    return util.import_app(self.app_uri)
